UPDATE Phones SET number=42856314 WHERE client_id=1;
UPDATE Clients SET name='James' WHERE name='Harry';
UPDATE Accounts SET alias='wingardium leviosa' WHERE idAccounts=2;
UPDATE Suscriptions SET service="Disney Plus" WHERE monthly_cost>=2;
UPDATE Debts SET deadline='01/01/20024' WHERE money=500;
UPDATE Cards SET number=147852369 WHERE idCards=5;
UPDATE Transactions SET destinationCBU=456456456 WHERE idTransactions=1;
UPDATE Assistants SET name='Snape' WHERE lastName='Severous';
UPDATE Managers SET phone_id=2 WHERE name='Albus';
UPDATE Benefits SET benefit='Free Cinema Ticket' WHERE idBenefits=2;
UPDATE Investments SET description='Bitcoin' WHERE money=500;
UPDATE Payments SET place='Burger King' WHERE idPayments=5;